# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Paschalis Agapitos" # Your name
  description: "My personal academic website"
  image: img/prof_pic.jpg
  page-navigation: true
  twitter-card:
    creator: "@paschalisag"
  open-graph: true
  repo-url: https://github.com/PaschalisAg/paschalisag.github.io
  cookie-consent:
    type: express
    style: interstitial
    palette: dark
  google-analytics: "G-16B83QME0W"


  
  favicon: img/favicon_network.png
  
  # start of the navigation bar at the top of the website
  search:
    location: navbar
    type: textbox
    copy-button: true
  navbar:
    background: primary
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      # - text: "Projects"
      #   href: projects/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    # aria-label: make items accessible for screen readers
    right:
      - icon: github
        href: https://github.com/PaschalisAg
        aria-label: Github
      - icon: twitter
        href: https://twitter.com/paschalisag
        aria-label: Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/paschalis-agapitos-1b5284217/
        aria-label: Linkedin
      - icon: envelope
        aria-label: email
        href: "mailto:paschalis.agapitos@dipc.org"  
  

# # Don't touch unless you know what you are doing :) ------------

  page-footer: 
    left: |
      <span class="faux-block">&#169; 2023 Marvin Schmitt CC BY-SA 4.0</span>
    # center: |
      # <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    # right: |
      # <span class="faux-block"><a href="https://github.com/marvinschmitt/quarto-website-template/">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: auto

format:
  html:
    include-after-body:
      # <!-- Google tag (gtag.js) -->
      - text: |
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-16B83QME0W"></script>
          <script>
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-16B83QME0W');
          </script>
    fontsize: 1.1em
    highlight-style: a11y # set the theme to be adaptive for syntax highlighting

    theme:
      light: [flatly, html/light-styles.scss]
      dark: [darkly, html/dark-styles.scss]
    smooth-scroll: true
    df-print: kable
    css: styles.css
    code-link: true
    anchor-sections: true
    # fig-cap-location: margin
    # reference-location: margin
    footnotes-hover: true